

## Geocode the names
get_geocoded_names <- function(identifier = "AL") {

  
  ## Retail Centres
  rc <- st_read(paste0("Output Data/Retail Centres/", identifier, "_RC_Boundaries.gpkg"))
  
  # 1. Stage 1. Geocoding - getting city, county and state ----------

  ## Get centroids
  cent <- st_centroid(rc)
  ## Reverse geocode
  g <- reverse_geocode(cent, 1, FALSE)
  
  if(is.null(g) == TRUE) {
    print("API Key Expired")
  } else {
    
    ## Clean
    clean_rc <- rc %>% select(rcID, rcName, n.pts, County, State)
    rc_clean <- cbind(clean_rc, g)
    rc_clean <- rc_clean %>%
      select(-c(id, rank, street, address, type, house_number, postal_code, district, county, state, country,
                distance, lng_access, lat_access, lng_position, lat_position))  %>%
     dplyr::rename(county = County, state = State)
    
    # 2. Getting street names for centres (based on most the street mo --------
    
    ## Read in points and intersect w/ retail centres
    pts <- read_points(identifier)
    pts_clean <- pts %>% 
      select(safegraph_place_id, street_address, location_name, sub_category, city, region, postal_code) %>%
      mutate(street_address_clean = sub(".*? ", "", street_address)) %>%
      select(-c(street_address))
    m <- st_intersection(pts_clean, rc)
  
    ## Identify the 'major' street of each retail centre
    streets <- m %>% 
      as.data.frame() %>%
      dplyr::select(street_address_clean, rcID) %>%
      group_by(rcID) %>%
      dplyr::count(street_address_clean) %>%
      top_n(n = 1) %>%
      group_by(rcID) %>%
      dplyr::summarise(street_address_clean = paste0(street_address_clean, collapse = " / "), n = n, .groups = "keep") %>%
      distinct(street_address_clean) %>%
      dplyr::rename(street_name = street_address_clean)
    rc_clean <- merge(rc_clean, streets, by = "rcID")
    

    # 3. Stage 3. Identifying the Malls -----------------------------------------------------------------------
    
    ## Extract malls for the AoI
    malls <- st_read("Output Data/US_Malls.gpkg")
    malls <- malls %>% 
      filter(region == identifier) %>%
      select(location_name, sub_category) %>%
      st_transform(4326)
    
    ## Identify the rc's that contain a mall
    rc_malls <- st_intersection(malls, rc)
    rc_malls <- rc_malls %>%
      as.data.frame() %>%
      select(rcID, location_name) %>%
      group_by(rcID) %>%
      distinct(location_name) %>%
      dplyr::summarise(location_name = paste0(location_name, collapse = " & "))
      #mutate(location_name = stringr::str_trunc(location_name, 70))
    
    ## Sort out location names - we only want max two malls, and remove any NA's generated by string split
    vec <- rc_malls$location_name
    
    p1 <- vapply(strsplit(vec, '&'), function(x)
      paste(x[seq.int(2)], collapse='&'), character(1L))
    p2 <- vapply(strsplit(p1, 'NA'), function(x)
      paste(x[seq.int(1)], collapse=''), character(1L))
    location_name_v2 <- str_sub(p2, 1, nchar(p2) -1)
    location_name_v2
    rc_malls <- cbind(rc_malls, location_name_v2)
    rc_malls <- rc_malls %>%
      select(-c(location_name)) %>%
      rename(location_name = location_name_v2)
    rc_clean <- merge(rc_clean, rc_malls, by = "rcID", all.x = TRUE)
    
    ## Create identifier as to whether a centre is a mall or not
    rc_clean <- rc_clean %>%
      mutate(mall_identifier = case_when(is.na(location_name) ~ "NO MALL",
                                         !is.na(location_name) ~ "MALL"))
    
    
    # 4. Identifying those in Major Cities  -------------------------------------------------
    
    ## Read in the city
    query <- paste0("select* from CityBoundaries where ST = '", identifier, "'")
    cities <- st_read("Input Data/US_Cities/CityBoundaries.shp", query = query)
    cities <- cities %>%
      select(NAME) %>%
      dplyr::rename(city_name = NAME) %>%
      st_transform(4326)
    
    ## Identify those centres that are in a major city
    rc_cities <- st_intersection(cities, rc)
    rc_cities <- rc_cities %>%
      as.data.frame() %>%
      select(rcID, city_name) %>%
      group_by(rcID) %>%
      distinct(city_name) %>%
      dplyr::summarise(city_name = paste0(city_name, collapse = " & "))
    rc_clean <- merge(rc_clean, rc_cities, by = "rcID", all.x = TRUE)
    
    ## Create identifier as to whether a centre is in a major city or not
    rc_clean <- rc_clean %>%
      mutate(city_identifier = case_when(is.na(city_name) ~ "NO CITY",
                                         !is.na(city_name) ~ "CITY"))
    
    # 5. Identifying the larges in places outside of Cities -------------------

    
    ## Create lookup of whether rc is largest in place
    tops <- rc_clean %>%
      as.data.frame() %>%
      group_by(city) %>%
      top_n(1, wt = n.pts) %>%
      mutate(hier_identifier = "LARGEST") %>%
      select(rcID, hier_identifier)
    rc_clean <- merge(rc_clean, tops, by = "rcID", all.x = TRUE)

    # 6. Create Retail Centre Names -------------------------------------------

    ## Conditional Naming
    out <- rc_clean %>%
      dplyr::rename(rcID_full = rcID, city = city.x) %>%
      select(-c(city.y)) %>%
      mutate(rcID = substr(rcID_full, 10, 12:13)) %>%
      mutate(rcID = gsub("_", "", rcID)) %>%
      mutate(rcName_test = case_when(city_identifier == "CITY" & mall_identifier == "NO MALL" & n.pts < 1000 & is.na(hier_identifier) ~ paste0(street_name, ",", " ", city_name, ",", " ", state),
                                     city_identifier == "CITY" & mall_identifier == "NO MALL" & n.pts < 1000 & hier_identifier == "LARGEST" ~ paste0(city,",", " ", state),
                                     city_identifier == "CITY" & mall_identifier == "MALL" & n.pts < 1000 & is.na(hier_identifier) ~ paste0(location_name, ",", " ", city_name, ",", " ", state),
                                     city_identifier == "CITY" & mall_identifier == "MALL" & n.pts < 1000 & hier_identifier == "LARGEST" ~ paste0(city, ",", " ", state),
                                     city_identifier == "CITY" & mall_identifier == "MALL" & n.pts >= 1000 ~ paste0(city, " ", "City",  ",", " ", state),
                                     city_identifier == "NO CITY" & mall_identifier == "MALL" ~ paste0(location_name, ",", " ", city, ",", " ", state),
                                     city_identifier == "NO CITY" & mall_identifier == "NO MALL" & hier_identifier == "LARGEST" ~ paste0(city, ",", " ", state),
                                     city_identifier == "NO CITY" & mall_identifier == "NO MALL" & is.na(hier_identifier) ~ paste0(street_name, ",", " ", city, ",", " ", state))) %>%
      group_by(rcName_test) %>%
      add_count(rcName_test) %>%
      group_by(rcName_test, n) %>%
      arrange(desc(n.pts)) %>%
      dplyr::mutate(uniqueID = sequence(n())) %>%
      mutate(rcName = case_when(n == 1 ~ paste0(rcName_test),
                                   n > 1 ~ paste0(rcName_test, " ", "(", uniqueID, ")"))) %>%
      select(rcID_full, rcID, rcName, n.pts, street_name, city, county, state) %>%
      rename(street = street_name, place = city) %>%
      mutate(rcID = as.integer(rcID)) %>%
      arrange(rcID)

    # 4. Write Out ------------------------------------------------------------
    st_write(out, paste0("Output Data/Retail Centres/Named/", identifier, "_RC_Named.gpkg"), append = FALSE)
    
  }
}

